# 端口号
server:
  port: 8761
# 服务注册相关配置
eureka:
  # 服务实例主机名
  instance:
    hostname: localhost
  # 服务提供者配置
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: true
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: true
    # 服务注册中心地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/